apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2  # Run 2 instances of the app
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: nandhini1694/devops-project  # Your Docker image from Docker Hub
        ports:
        - containerPort: 3001

