apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80  # External port
      targetPort: 3001  # Port inside container
  type: NodePort  # Exposes the service on a port accessible from outside

